// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
// ignore_for_file: type=lint, unused_import
import 'dart:ffi' as ffi;

/// Public AES API — the only things Dart will call
@ffi.Native<
  ffi.Int Function(
    ffi.Pointer<uchar_t>,
    ffi.Pointer<uchar_t>,
    ffi.Int,
    ffi.Pointer<ffi.Void>,
  )
>()
external int aes_encrypt(
  ffi.Pointer<uchar_t> input,
  ffi.Pointer<uchar_t> output,
  int length,
  ffi.Pointer<ffi.Void> key,
);

@ffi.Native<
  ffi.Int Function(
    ffi.Pointer<uchar_t>,
    ffi.Pointer<uchar_t>,
    ffi.Int,
    ffi.Pointer<ffi.Void>,
  )
>()
external int aes_decrypt(
  ffi.Pointer<uchar_t> input,
  ffi.Pointer<uchar_t> output,
  int length,
  ffi.Pointer<ffi.Void> key,
);

@ffi.Native<
  ffi.Int Function(ffi.Pointer<ffi.Void>, ffi.Pointer<uchar_t>, ffi.Size)
>()
external int aes_set_key(
  ffi.Pointer<ffi.Void> key_struct,
  ffi.Pointer<uchar_t> key_str,
  int key_len,
);

@ffi.Native<ffi.Int Function(ffi.Pointer<ffi.Void>)>()
external int aes_free_key(ffi.Pointer<ffi.Void> key_struct);

/// Public AES API — the only things Dart will call
@ffi.Native<
  ffi.Int Function(
    ffi.Pointer<uchar_t>,
    ffi.Pointer<uchar_t>,
    ffi.Int,
    ffi.Pointer<ffi.Void>,
  )
>()
external int des_encrypt(
  ffi.Pointer<uchar_t> input,
  ffi.Pointer<uchar_t> output,
  int length,
  ffi.Pointer<ffi.Void> key,
);

@ffi.Native<
  ffi.Int Function(
    ffi.Pointer<uchar_t>,
    ffi.Pointer<uchar_t>,
    ffi.Int,
    ffi.Pointer<ffi.Void>,
  )
>()
external int des_decrypt(
  ffi.Pointer<uchar_t> input,
  ffi.Pointer<uchar_t> output,
  int length,
  ffi.Pointer<ffi.Void> key,
);

@ffi.Native<
  ffi.Int Function(ffi.Pointer<ffi.Void>, ffi.Pointer<uchar_t>, ffi.Size)
>()
external int des_set_key(
  ffi.Pointer<ffi.Void> key_struct,
  ffi.Pointer<uchar_t> key_str,
  int key_len,
);

@ffi.Native<ffi.Int Function(ffi.Pointer<ffi.Void>)>()
external int des_free_key(ffi.Pointer<ffi.Void> key_struct);

/// Public AES API — the only things Dart will call
@ffi.Native<
  ffi.Int Function(
    ffi.Pointer<uchar_t>,
    ffi.Pointer<uchar_t>,
    ffi.Int,
    ffi.Pointer<ffi.Void>,
  )
>()
external int tdes_encrypt(
  ffi.Pointer<uchar_t> input,
  ffi.Pointer<uchar_t> output,
  int length,
  ffi.Pointer<ffi.Void> key,
);

@ffi.Native<
  ffi.Int Function(
    ffi.Pointer<uchar_t>,
    ffi.Pointer<uchar_t>,
    ffi.Int,
    ffi.Pointer<ffi.Void>,
  )
>()
external int tdes_decrypt(
  ffi.Pointer<uchar_t> input,
  ffi.Pointer<uchar_t> output,
  int length,
  ffi.Pointer<ffi.Void> key,
);

@ffi.Native<
  ffi.Int Function(ffi.Pointer<ffi.Void>, ffi.Pointer<uchar_t>, ffi.Size)
>()
external int tdes_set_key(
  ffi.Pointer<ffi.Void> key_struct,
  ffi.Pointer<uchar_t> key_str,
  int key_len,
);

@ffi.Native<ffi.Int Function(ffi.Pointer<ffi.Void>)>()
external int tdes_free_key(ffi.Pointer<ffi.Void> key_struct);

/// Public AES API — the only things Dart will call
@ffi.Native<
  ffi.Int Function(
    ffi.Pointer<uchar_t>,
    ffi.Pointer<uchar_t>,
    ffi.Int,
    ffi.Pointer<ffi.Void>,
  )
>()
external int blowfish_encrypt(
  ffi.Pointer<uchar_t> input,
  ffi.Pointer<uchar_t> output,
  int length,
  ffi.Pointer<ffi.Void> key,
);

@ffi.Native<
  ffi.Int Function(
    ffi.Pointer<uchar_t>,
    ffi.Pointer<uchar_t>,
    ffi.Int,
    ffi.Pointer<ffi.Void>,
  )
>()
external int blowfish_decrypt(
  ffi.Pointer<uchar_t> input,
  ffi.Pointer<uchar_t> output,
  int length,
  ffi.Pointer<ffi.Void> key,
);

@ffi.Native<
  ffi.Int Function(ffi.Pointer<ffi.Void>, ffi.Pointer<uchar_t>, ffi.Size)
>()
external int blowfish_set_key(
  ffi.Pointer<ffi.Void> key_struct,
  ffi.Pointer<uchar_t> key_str,
  int key_len,
);

@ffi.Native<ffi.Int Function(ffi.Pointer<ffi.Void>)>()
external int blowfish_free_key(ffi.Pointer<ffi.Void> key_struct);

/// Public AES API — the only things Dart will call
@ffi.Native<
  ffi.Int Function(
    ffi.Pointer<uchar_t>,
    ffi.Pointer<uchar_t>,
    ffi.Int,
    ffi.Pointer<ffi.Void>,
  )
>()
external int rc4_encrypt(
  ffi.Pointer<uchar_t> input,
  ffi.Pointer<uchar_t> output,
  int length,
  ffi.Pointer<ffi.Void> key,
);

@ffi.Native<
  ffi.Int Function(
    ffi.Pointer<uchar_t>,
    ffi.Pointer<uchar_t>,
    ffi.Int,
    ffi.Pointer<ffi.Void>,
  )
>()
external int rc4_decrypt(
  ffi.Pointer<uchar_t> input,
  ffi.Pointer<uchar_t> output,
  int length,
  ffi.Pointer<ffi.Void> key,
);

@ffi.Native<
  ffi.Int Function(ffi.Pointer<ffi.Void>, ffi.Pointer<uchar_t>, ffi.Size)
>()
external int rc4_set_key(
  ffi.Pointer<ffi.Void> key_struct,
  ffi.Pointer<uchar_t> key_str,
  int key_len,
);

@ffi.Native<ffi.Int Function(ffi.Pointer<ffi.Void>)>()
external int rc4_free_key(ffi.Pointer<ffi.Void> key_struct);

/// Public AES API — the only things Dart will call
@ffi.Native<
  ffi.Int Function(
    ffi.Pointer<uchar_t>,
    ffi.Pointer<uchar_t>,
    ffi.Int,
    ffi.Pointer<ffi.Void>,
  )
>()
external int redpike_encrypt(
  ffi.Pointer<uchar_t> input,
  ffi.Pointer<uchar_t> output,
  int length,
  ffi.Pointer<ffi.Void> key,
);

@ffi.Native<
  ffi.Int Function(
    ffi.Pointer<uchar_t>,
    ffi.Pointer<uchar_t>,
    ffi.Int,
    ffi.Pointer<ffi.Void>,
  )
>()
external int redpike_decrypt(
  ffi.Pointer<uchar_t> input,
  ffi.Pointer<uchar_t> output,
  int length,
  ffi.Pointer<ffi.Void> key,
);

@ffi.Native<
  ffi.Int Function(ffi.Pointer<ffi.Void>, ffi.Pointer<uchar_t>, ffi.Size)
>()
external int redpike_set_key(
  ffi.Pointer<ffi.Void> key_struct,
  ffi.Pointer<uchar_t> key_str,
  int key_len,
);

@ffi.Native<ffi.Int Function(ffi.Pointer<ffi.Void>)>()
external int redpike_free_key(ffi.Pointer<ffi.Void> key_struct);

/// Public AES API — the only things Dart will call
@ffi.Native<
  ffi.Int Function(
    ffi.Pointer<uchar_t>,
    ffi.Pointer<uchar_t>,
    ffi.Int,
    ffi.Pointer<ffi.Void>,
  )
>()
external int tea_encrypt(
  ffi.Pointer<uchar_t> input,
  ffi.Pointer<uchar_t> output,
  int length,
  ffi.Pointer<ffi.Void> key,
);

@ffi.Native<
  ffi.Int Function(
    ffi.Pointer<uchar_t>,
    ffi.Pointer<uchar_t>,
    ffi.Int,
    ffi.Pointer<ffi.Void>,
  )
>()
external int tea_decrypt(
  ffi.Pointer<uchar_t> input,
  ffi.Pointer<uchar_t> output,
  int length,
  ffi.Pointer<ffi.Void> key,
);

@ffi.Native<
  ffi.Int Function(ffi.Pointer<ffi.Void>, ffi.Pointer<uchar_t>, ffi.Size)
>()
external int tea_set_key(
  ffi.Pointer<ffi.Void> key_struct,
  ffi.Pointer<uchar_t> key_str,
  int key_len,
);

@ffi.Native<ffi.Int Function(ffi.Pointer<ffi.Void>)>()
external int tea_free_key(ffi.Pointer<ffi.Void> key_struct);

@ffi.Native<
  ffi.Int Function(
    ffi.Pointer<uchar_t>,
    ffi.Pointer<uchar_t>,
    ffi.Int,
    ffi.Pointer<ffi.Void>,
  )
>()
external int xtea_encrypt(
  ffi.Pointer<uchar_t> input,
  ffi.Pointer<uchar_t> output,
  int length,
  ffi.Pointer<ffi.Void> key,
);

@ffi.Native<
  ffi.Int Function(
    ffi.Pointer<uchar_t>,
    ffi.Pointer<uchar_t>,
    ffi.Int,
    ffi.Pointer<ffi.Void>,
  )
>()
external int xtea_decrypt(
  ffi.Pointer<uchar_t> input,
  ffi.Pointer<uchar_t> output,
  int length,
  ffi.Pointer<ffi.Void> key,
);

@ffi.Native<
  ffi.Int Function(ffi.Pointer<ffi.Void>, ffi.Pointer<uchar_t>, ffi.Size)
>()
external int xtea_set_key(
  ffi.Pointer<ffi.Void> key_struct,
  ffi.Pointer<uchar_t> key_str,
  int key_len,
);

@ffi.Native<ffi.Int Function(ffi.Pointer<ffi.Void>)>()
external int xtea_free_key(ffi.Pointer<ffi.Void> key_struct);

@ffi.Native<ffi.Pointer<ffi.Void> Function(ffi.Pointer<uchar_t>, ffi.Size)>()
external ffi.Pointer<ffi.Void> aes_new_key(
  ffi.Pointer<uchar_t> key,
  int key_len,
);

@ffi.Native<ffi.Void Function(ffi.Pointer<ffi.Void>)>()
external void aes_destroy_key(ffi.Pointer<ffi.Void> k);

@ffi.Native<ffi.Pointer<ffi.Void> Function(ffi.Pointer<uchar_t>, ffi.Size)>()
external ffi.Pointer<ffi.Void> des_new_key(
  ffi.Pointer<uchar_t> key,
  int key_len,
);

@ffi.Native<ffi.Void Function(ffi.Pointer<ffi.Void>)>()
external void des_destroy_key(ffi.Pointer<ffi.Void> k);

@ffi.Native<ffi.Pointer<ffi.Void> Function(ffi.Pointer<uchar_t>, ffi.Size)>()
external ffi.Pointer<ffi.Void> tdes_new_key(
  ffi.Pointer<uchar_t> key,
  int key_len,
);

@ffi.Native<ffi.Void Function(ffi.Pointer<ffi.Void>)>()
external void tdes_destroy_key(ffi.Pointer<ffi.Void> k);

@ffi.Native<ffi.Pointer<ffi.Void> Function(ffi.Pointer<uchar_t>, ffi.Size)>()
external ffi.Pointer<ffi.Void> blowfish_new_key(
  ffi.Pointer<uchar_t> key,
  int key_len,
);

@ffi.Native<ffi.Void Function(ffi.Pointer<ffi.Void>)>()
external void blowfish_destroy_key(ffi.Pointer<ffi.Void> k);

@ffi.Native<ffi.Pointer<ffi.Void> Function(ffi.Pointer<uchar_t>, ffi.Size)>()
external ffi.Pointer<ffi.Void> rc4_new_key(
  ffi.Pointer<uchar_t> key,
  int key_len,
);

@ffi.Native<ffi.Void Function(ffi.Pointer<ffi.Void>)>()
external void rc4_destroy_key(ffi.Pointer<ffi.Void> k);

@ffi.Native<ffi.Pointer<ffi.Void> Function(ffi.Pointer<uchar_t>, ffi.Size)>()
external ffi.Pointer<ffi.Void> redpike_new_key(
  ffi.Pointer<uchar_t> key,
  int key_len,
);

@ffi.Native<ffi.Void Function(ffi.Pointer<ffi.Void>)>()
external void redpike_destroy_key(ffi.Pointer<ffi.Void> k);

@ffi.Native<ffi.Pointer<ffi.Void> Function(ffi.Pointer<uchar_t>, ffi.Size)>()
external ffi.Pointer<ffi.Void> tea_new_key(
  ffi.Pointer<uchar_t> key,
  int key_len,
);

@ffi.Native<ffi.Void Function(ffi.Pointer<ffi.Void>)>()
external void tea_destroy_key(ffi.Pointer<ffi.Void> k);

@ffi.Native<ffi.Pointer<ffi.Void> Function(ffi.Pointer<uchar_t>, ffi.Size)>()
external ffi.Pointer<ffi.Void> xtea_new_key(
  ffi.Pointer<uchar_t> key,
  int key_len,
);

@ffi.Native<ffi.Void Function(ffi.Pointer<ffi.Void>)>()
external void xtea_destroy_key(ffi.Pointer<ffi.Void> k);

/// If you need to allocate a key struct from Dart:
/// (you'll need to know how big AesKey is — see note below)
/// size_t aes_key_size(void);
@ffi.Native<
  ffi.Int Function(
    ffi.Pointer<ffi.Char>,
    ffi.Pointer<uchar_t>,
    ffi.Pointer<uchar_t>,
    ffi.Pointer<uchar_t>,
    ffi.Size,
  )
>()
external int encrypt_image_file(
  ffi.Pointer<ffi.Char> name,
  ffi.Pointer<uchar_t> input_path,
  ffi.Pointer<uchar_t> output_path,
  ffi.Pointer<uchar_t> _key,
  int _key_len,
);

@ffi.Native<
  ffi.Int Function(
    ffi.Pointer<ffi.Char>,
    ffi.Pointer<uchar_t>,
    ffi.Pointer<uchar_t>,
    ffi.Pointer<uchar_t>,
    ffi.Size,
  )
>()
external int decrypt_image_file(
  ffi.Pointer<ffi.Char> name,
  ffi.Pointer<uchar_t> input_path,
  ffi.Pointer<uchar_t> output_path,
  ffi.Pointer<uchar_t> _key,
  int _key_len,
);

@ffi.Native<ffi.Int Function(ffi.Pointer<ffi.Char>)>()
external int get_block_size(ffi.Pointer<ffi.Char> cipher_name);

@ffi.Native<ffi.Int Function(ffi.Pointer<ffi.Char>)>()
external int get_key_size(ffi.Pointer<ffi.Char> cipher_name);

/// Hashing
@ffi.Native<ffi.Int Function(ffi.Pointer<ffi.Char>)>()
external int get_digest_size(ffi.Pointer<ffi.Char> hash_name);

@ffi.Native<
  ffi.Void Function(ffi.Pointer<uchar_t>, ffi.Int, ffi.Pointer<uchar_t>)
>()
external void md4_hash(
  ffi.Pointer<uchar_t> M,
  int N,
  ffi.Pointer<uchar_t> output,
);

@ffi.Native<
  ffi.Void Function(ffi.Pointer<uchar_t>, ffi.Int, ffi.Pointer<uchar_t>)
>()
external void md5_hash(
  ffi.Pointer<uchar_t> M,
  int N,
  ffi.Pointer<uchar_t> output,
);

@ffi.Native<
  ffi.Void Function(ffi.Pointer<uchar_t>, ffi.Size, ffi.Pointer<uchar_t>)
>()
external void sha256_hash(
  ffi.Pointer<uchar_t> data,
  int len,
  ffi.Pointer<uchar_t> digest,
);

@ffi.Native<
  ffi.Void Function(ffi.Pointer<uchar_t>, ffi.Size, ffi.Pointer<uchar_t>)
>()
external void sha512_hash(
  ffi.Pointer<uchar_t> data,
  int len,
  ffi.Pointer<uchar_t> digest,
);

@ffi.Native<
  ffi.Int Function(
    ffi.Pointer<ffi.Char>,
    ffi.Pointer<ffi.Char>,
    ffi.Pointer<uchar_t>,
    ffi.Pointer<uchar_t>,
    ffi.Pointer<uchar_t>,
    ffi.Int,
    ffi.Pointer<ffi.Void>,
  )
>()
external int cipher_encrypt_mode(
  ffi.Pointer<ffi.Char> cipher,
  ffi.Pointer<ffi.Char> mode,
  ffi.Pointer<uchar_t> input,
  ffi.Pointer<uchar_t> output,
  ffi.Pointer<uchar_t> iv,
  int length,
  ffi.Pointer<ffi.Void> key,
);

@ffi.Native<
  ffi.Int Function(
    ffi.Pointer<ffi.Char>,
    ffi.Pointer<ffi.Char>,
    ffi.Pointer<uchar_t>,
    ffi.Pointer<uchar_t>,
    ffi.Pointer<uchar_t>,
    ffi.Int,
    ffi.Pointer<ffi.Void>,
  )
>()
external int cipher_decrypt_mode(
  ffi.Pointer<ffi.Char> cipher,
  ffi.Pointer<ffi.Char> mode,
  ffi.Pointer<uchar_t> input,
  ffi.Pointer<uchar_t> output,
  ffi.Pointer<uchar_t> iv,
  int length,
  ffi.Pointer<ffi.Void> key,
);

@ffi.Native<ffi.Int Function(ffi.Pointer<ffi.Char>)>()
external int has_iv(ffi.Pointer<ffi.Char> mode);

/// Opaque handles — Dart only ever sees pointers to these
/// typedef struct AesKey AesKey;
/// typedef struct DesKey DesKey;
/// typedef struct Rc4Key Rc4Key;
/// typedef struct RedpikeKey RedpikeKey;
/// typedef struct TeaKey TeaKey;
/// typedef struct XTeaKey XTeaKey;
typedef uchar_t = ffi.UnsignedChar;
typedef Dartuchar_t = int;
