#include "hash.h"
#include <math.h>


// TODO : fix the bug in sha256 (we are not yet updating the input_padded blocks )
// TODO : also look for a way to refactor the multiple functions that we are constantly using 
// TODO : re-implement sha256 with the logic in sha512 ???
// screw this all 







// from the official standard : 
// " Each algorithm can be described in two stages: preprocessing and hash computation "

// "Preprocessing involves padding a message, parsing the padded message into m-bit blocks, and
// setting initialization values to be used in the hash computation. "


// "The hash computation generates
// a message schedule from the padded message and uses that schedule, along with functions,
// constants, and word operations to iteratively generate a series of hash values. The final hash
// value generated by the hash computation is used to determine the message digest"

// we wrapped the whole thing with (uint32_t) in order to not get any UB  ... 
static uint32_t bytes_to_be(uchar_t input[4]) {
    return (uint32_t) (((uint32_t)input[0] << 24) | ((uint32_t)input[1] << 16) | ((uint32_t)input[2] << 8) | (uint32_t)input[3]) ;
}

// we wrapped the whole thing with (uint64_t) in order to not get any UB  ... 
// cuz when we shifted uchar_t by 24 it became an int which later caused headache and wasted hours in debugging :(
static uint64_t bytes_to_64be(uchar_t input[8]) {

    uint64_t a = ((uint64_t)input[0] << 24) | ((uint64_t)input[1] << 16) | ((uint64_t)input[2] << 8) | ((uint64_t)input[3] );
    uint64_t b = ((uint64_t)input[4] << 24) | ((uint64_t)input[5] << 16) | ((uint64_t)input[6] << 8) | ((uint64_t)input[7] );


    uint64_t result = (a << 32) | b  ; 


    return result ; 
}

// ????
static void be_to_bytes(uint32_t num , uchar_t input[4]) {
    input[0] = (num & 0xff000000 ) >> 24 ;
    input[1] = (num & 0x00ff0000 ) >> 16 ;
    input[2] = (num & 0x0000ff00 ) >> 8 ;
    input[3] = (num & 0x000000ff )  ;
}
static void be64_to_bytes(uint64_t num , uchar_t input[8]) {
    input[0] = (num & 0xff00000000000000 ) >> 56 ;
    input[1] = (num & 0x00ff000000000000 ) >> 48 ;
    input[2] = (num & 0x0000ff0000000000 ) >> 40 ;
    input[3] = (num & 0x000000ff00000000 ) >> 32 ;
    input[4] = (num & 0x00000000ff000000 ) >> 24 ;
    input[5] = (num & 0x0000000000ff0000 ) >> 16 ;
    input[6] = (num & 0x000000000000ff00 ) >> 8 ;
    input[7] = (num & 0x00000000000000ff ) ;
}



// static uint32_t rotl_32bit(uint32_t a , uint32_t times) {
//     times %= 32 ;

//     if (!times)
//         return a ;


//     return ((a << times) | (a >> (32 - times))) ;
// }

// static uint64_t rotl_64bit(uint64_t a , uint32_t times) {
//     times %= 64 ;

//     if (!times)
//         return a ;


//     return ((a << times) | (a >> (64 - times))) ;
// }


static uint32_t rotr_32bit(uint32_t a , uint32_t times) {
    times %= 32 ;
    
    if (!times)
    return a ;
    
    
    return ((a >> times) | (a << (32 - times))) ;
}


static uint64_t rotr_64bit(uint64_t a , uint64_t times) {
    times %= 64 ;
    
    if (!times)
    return a ;
    
    
    return ((a >> times) | (a << (64 - times))) ;
}


static uint32_t shr_32bit(uint32_t a , uint32_t times) {
    times %= 32 ;
    return a >> times ;
}

static uint64_t shr_64bit(uint64_t a , uint64_t times) {
    times %= 64 ;
    return a >> times ;
}


// static uint32_t shl_32bit(uint32_t a , uint32_t times) {
//     times %= 32 ;
//     return a << times ;
// }
// static uint64_t shl_64bit(uint64_t a , uint64_t times) {
//     times %= 64 ;
//     return a << times ;
// }


static void Ch_sha256(uchar_t *x , uchar_t *y , uchar_t *z , uchar_t *result) {

    uchar_t temp1[4] ;
    for (int i = 0; i < 4; i++)
    {
        temp1[i] = x[i] & y[i] ;
    }

    uchar_t temp2[4] ;
    for (int i = 0; i < 4; i++)
    {
        temp2[i] = (~x[i]) & z[i] ;
    }

    for (int i = 0; i < 4; i++)
    {
        result[i] = temp1[i] ^ temp2[i] ;
    }

}


static void Maj_sha256(uchar_t *x , uchar_t *y , uchar_t *z , uchar_t *result) {

    uchar_t temp1[4] ;
    for (int i = 0; i < 4; i++)
    {
        temp1[i] = x[i] & y[i] ;
    }

    uchar_t temp2[4] ;
    for (int i = 0; i < 4; i++)
    {
        temp2[i] = x[i] & z[i] ;
    }
    
    uchar_t temp3[4] ;

    for (int i = 0; i < 4; i++)
    {
        temp3[i] = y[i] & z[i] ;
    }


    for (int i = 0; i < 4; i++)
    {
        result[i] = temp1[i] ^ temp2[i] ^ temp3[i] ;
    }


}



static uint32_t Sum0_256_sha256(uint32_t num) {
    return rotr_32bit(num , 2) ^ rotr_32bit(num , 13) ^ rotr_32bit(num , 22)   ; 
}


static uint32_t Sum1_256_sha256(uint32_t num) {
    return rotr_32bit(num , 6) ^ rotr_32bit(num , 11) ^ rotr_32bit(num , 25)   ; 
}


static uint32_t Sigma0_256_sha256(uint32_t num) {
    return rotr_32bit(num , 7) ^ rotr_32bit(num , 18) ^ shr_32bit(num , 3)   ; 
}

static uint32_t Sigma1_256_sha256(uint32_t num) {
    return rotr_32bit(num , 17) ^ rotr_32bit(num , 19) ^ shr_32bit(num , 10)   ; 
}

// maybe there is a better way to do this shit :
static void init_Hash_Values(uchar_t H[8*4]) {
    const int PRIMES_64[64] = {
        2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 
        31, 37, 41, 43, 47, 53, 59, 61, 67, 71, 
        73, 79, 83, 89, 97, 101, 103, 107, 109, 113, 
        127, 131, 137, 139, 149, 151, 157, 163, 167, 173, 
        179, 181, 191, 193, 197, 199, 211, 223, 227, 229, 
        233, 239, 241, 251, 257, 263, 269, 271, 277, 281, 
        283, 293, 307, 311
    };

    int b ;
    long double d ;  
    int j = 0 ;
    for (int i = 0; i < 8*4; i+=4)
    {
        d = sqrt(PRIMES_64[j]) * 4294967296 ;
        b = (uint32_t) d ;
        // printf(" b = %u \t %x  \n" , b , b) ; 
        be_to_bytes(b , H + i) ;
        j++ ;  

    }


}



static void init_K(uchar_t K[64*4]) {
    const int PRIMES_64[64] = {
        2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 
        31, 37, 41, 43, 47, 53, 59, 61, 67, 71, 
        73, 79, 83, 89, 97, 101, 103, 107, 109, 113, 
        127, 131, 137, 139, 149, 151, 157, 163, 167, 173, 
        179, 181, 191, 193, 197, 199, 211, 223, 227, 229, 
        233, 239, 241, 251, 257, 263, 269, 271, 277, 281, 
        283, 293, 307, 311
    };

    int b ;
    long double d ;  
    int j = 0 ; 
    for (int i = 0; i < 64*4; i+=4)
    {
        d = cbrt(PRIMES_64[j]) * 4294967296 ;
        b = (uint32_t) d ;
        // printf(" b = %u \t %x  \n" , b , b) ; 
        be_to_bytes(b , K + i) ; 
        j++ ; 
    }
        
}




uchar_t* sha256_padding(const uchar_t M[] , uint64_t b , uint64_t *output_length ) {
    // b number of bits ?
    // the specification says that it needs not be to be mulytiply of 8 ??? (pretty much weird)
    *output_length = b +64 +  (512 - ((b+64)  % 512)) ;
    // printf("b: %ld \n" , b) ; 
    // printf("calculated output length before: %ld \n" , *output_length) ; 
    uchar_t *output = malloc(*output_length * sizeof(uchar_t)  ) ;
    if (b % 8 == 0)
    {
        memcpy(output , M  , sizeof(uchar_t)* b / 8) ;
        // 512 / 8 = 64
        // this contains length % 64 bytes
        uint32_t temp = (b / 8) % 64  ;
        uint32_t index =  b / 8 ;

        output[index] = 0x80 ;
        index++ ;
        temp++ ;

        // 448 / 8 = 56
        while (temp % 64 != 56)
        {
            output[index] = 0x00 ;
            index++ ;
            temp++ ;
        }
        // append length now ... .???????????????????????
        
        
        output[index] =   (b & 0xff00000000000000 ) >> 56 ; 
        output[index+1] = (b & 0x00ff000000000000 ) >> 48 ; 
        output[index+2] = (b & 0x0000ff0000000000 ) >> 40; 
        output[index+3] = (b & 0x000000ff00000000 ) >> 32; 
            
        index += 4 ; 
            
        output[index] =   (b & 0x00000000ff000000 ) >> 24 ; 
        output[index+1] = (b & 0x0000000000ff0000 ) >> 16 ; 
        output[index+2] = (b & 0x000000000000ff00 ) >> 8; 
        output[index+3] = (b & 0x00000000000000ff ); 
        
        
        index += 4 ; 


        // printf("calculated output length : %ld \n" , *output_length ) ;
        // printf("calculated output length/8 : %ld \n" , *output_length / 8) ;
        // printf("index : %u \n" , index) ;
        *output_length = index *8; 
        // printf("calculated output length after: %ld in bytes : %ld \n" , *output_length , *output_length) ; 
        assert(index == *output_length / 8 && "these 2 should be equal ???") ;
    } else {
        // ????????????????????????
        // TODO : handle this case too ...
        // ????????????????????????
        printf("not implemented (my pc works with only 8 bits :( \n")  ;
        exit(12) ;
    }

    return output ;

}



void sha256_hash(const uchar_t* data, size_t len, uchar_t digest[32]) {
    
    uchar_t H[8*4] ; 
    uchar_t W[64*4] ; 
    uchar_t K[64*4] ; 

    init_K(K) ;
    init_Hash_Values(H) ;


    uint64_t output_length  ; 
    uchar_t *input_padded = sha256_padding(data , 8*len , &output_length) ; 
    output_length /= 8 ; 

    // PRINT_ARRAY(input_padded , output_length , "%.02x") ; 
    uint32_t a , b , c , d , e ,f , g, h ;

    // printf("N =  %d\n" , output_length) ; 
    // printf("here you go looping from 0 to N/(16*4)-1 : %d\n" , output_length/(16*4)-1) ; 
    for (size_t i = 0; i <= output_length/(16*4)-1; i++)
    {

        for (size_t t = 0; t < 16; t++)
        {
            // FIX : man i wouldnt messed it up if i did it in go or sum the first time ..
            // the input_padded bloc must get updated aka in this case multiplied by (i* 16 * 4)
            memcpy(W + (t*4)  , input_padded + (t*4 ) + (i * 16*4)  , sizeof(uchar_t ) * 4 * 1) ; 
        }
        for (size_t t = 16; t < 64; t++)
        {
            uint32_t result = Sigma1_256_sha256(bytes_to_be(W + (t -2)*4)) + bytes_to_be(W + (t -7)*4) + Sigma0_256_sha256(bytes_to_be(W + (t -15)*4)) + bytes_to_be(W + (t -16)*4)    ; 
            be_to_bytes(result , W + t*4 ) ;
        }
        
        a = bytes_to_be(H + 0*4) ; 
        b = bytes_to_be(H + 1*4) ; 
        c = bytes_to_be(H + 2*4) ; 
        d = bytes_to_be(H + 3*4) ; 
        e = bytes_to_be(H + 4*4) ; 
        f = bytes_to_be(H + 5*4) ; 
        g = bytes_to_be(H + 6*4) ; 
        h = bytes_to_be(H + 7*4) ; 
        
        
        
        for (size_t t = 0; t < 64; t++)
        {

            uchar_t a_bytes[4] ;
            uchar_t b_bytes[4] ;
            uchar_t c_bytes[4] ;
            uchar_t e_bytes[4] ;
            uchar_t f_bytes[4] ;
            uchar_t g_bytes[4] ;
            uchar_t result[4] ;
            be_to_bytes(e , e_bytes) ; 
            be_to_bytes(f , f_bytes) ; 
            be_to_bytes(g , g_bytes) ; 
            
            Ch_sha256(e_bytes , f_bytes , g_bytes , result) ;
            
            uint32_t T1 = h + Sum1_256_sha256(e) + bytes_to_be(result) + bytes_to_be(K + t*4) + bytes_to_be(W + t*4)   ;  
            
            be_to_bytes(a , a_bytes) ; 
            be_to_bytes(b , b_bytes) ; 
            be_to_bytes(c , c_bytes) ; 
            
            Maj_sha256(a_bytes , b_bytes , c_bytes , result) ; 
            uint32_t T2 =  Sum0_256_sha256(a) + bytes_to_be(result)    ;  
            
            h = g ;
            
            g = f ; 
            
            f = e ; 
            
            e = d + T1 ; 
            
            d = c ; 
            
            c = b ;
            
            b = a ; 
            
            a = T1 + T2 ;

        }

        be_to_bytes( a  +  bytes_to_be(H + 0*4)  ,H + 0*4 ) ; 
        be_to_bytes( b  +  bytes_to_be(H + 1*4)  ,H + 1*4 ) ; 
        be_to_bytes( c  +  bytes_to_be(H + 2*4)  ,H + 2*4 ) ; 
        be_to_bytes( d  +  bytes_to_be(H + 3*4)  ,H + 3*4 ) ; 
        be_to_bytes( e  +  bytes_to_be(H + 4*4)  ,H + 4*4 ) ; 
        be_to_bytes( f  +  bytes_to_be(H + 5*4)  ,H + 5*4 ) ; 
        be_to_bytes( g  +  bytes_to_be(H + 6*4)  ,H + 6*4 ) ; 
        be_to_bytes( h  +  bytes_to_be(H + 7*4)  ,H + 7*4 ) ; 
        
    }
    memcpy(digest , H , sizeof(uchar_t)*8*4) ; 

    free(input_padded) ; 
}




static uint64_t Ch_sha512(uint64_t x , uint64_t y , uint64_t z ) {
    return (x & y) ^ (~x & z) ; 
}


static uint64_t Maj_sha512(uint64_t x , uint64_t y , uint64_t z ) {

    return (x & y) ^ (x & z) ^ (y & z) ; 
}



static uint64_t Sum0_512_sha512(uint64_t num) {
    return rotr_64bit(num , 28) ^ rotr_64bit(num , 34) ^ rotr_64bit(num , 39)   ; 
}


static uint64_t Sum1_512_sha512(uint64_t num) {
    return rotr_64bit(num , 14) ^ rotr_64bit(num , 18) ^ rotr_64bit(num , 41)   ; 
}


static uint64_t Sigma0_512_sha512(uint64_t num) {
    return rotr_64bit(num , 1) ^ rotr_64bit(num , 8) ^ shr_64bit(num , 7)   ; 
}

static uint64_t Sigma1_512_sha512(uint64_t num) {
    return rotr_64bit(num , 19) ^ rotr_64bit(num , 61) ^ shr_64bit(num , 6)   ; 
}


static void init_K_sha512(uint64_t K[80]) {

    const uint64_t SHA512_K[80] = {
        0x428a2f98d728ae22ULL, 0x7137449123ef65cdULL, 0xb5c0fbcfec4d3b2fULL, 0xe9b5dba58189dbbcULL,
        0x3956c25bf348b538ULL, 0x59f111f1b605d019ULL, 0x923f82a4af194f9bULL, 0xab1c5ed5da6d8118ULL,
        0xd807aa98a3030242ULL, 0x12835b0145706fbeULL, 0x243185be4ee4b28cULL, 0x550c7dc3d5ffb4e2ULL,
        0x72be5d74f27b896fULL, 0x80deb1fe3b1696b1ULL, 0x9bdc06a725c71235ULL, 0xc19bf174cf692694ULL,
        0xe49b69c19ef14ad2ULL, 0xefbe4786384f25e3ULL, 0x0fc19dc68b8cd5b5ULL, 0x240ca1cc77ac9c65ULL,
        0x2de92c6f592b0275ULL, 0x4a7484aa6ea6e483ULL, 0x5cb0a9dcbd41fbd4ULL, 0x76f988da831153b5ULL,
        0x983e5152ee66dfabULL, 0xa831c66d2db43210ULL, 0xb00327c898fb213fULL, 0xbf597fc7beef0ee4ULL,
        0xc6e00bf33da88fc2ULL, 0xd5a79147930aa725ULL, 0x06ca6351e003826fULL, 0x142929670a0e6e70ULL,
        0x27b70a8546d22ffcULL, 0x2e1b21385c26c926ULL, 0x4d2c6dfc5ac42aedULL, 0x53380d139d95b3dfULL,
        0x650a73548baf63deULL, 0x766a0abb3c77b2a8ULL, 0x81c2c92e47edaee6ULL, 0x92722c851482353bULL,
        0xa2bfe8a14cf10364ULL, 0xa81a664bbc423001ULL, 0xc24b8b70d0f89791ULL, 0xc76c51a30654be30ULL,
        0xd192e819d6ef5218ULL, 0xd69906245565a910ULL, 0xf40e35855771202aULL, 0x106aa07032bbd1b8ULL,
        0x19a4c116b8d2d0c8ULL, 0x1e376c085141ab53ULL, 0x2748774cdf8eeb99ULL, 0x34b0bcb5e19b48a8ULL,
        0x391c0cb3c5c95a63ULL, 0x4ed8aa4ae3418acbULL, 0x5b9cca4f7763e373ULL, 0x682e6ff3d6b2b8a3ULL,
        0x748f82ee5defb2fcULL, 0x78a5636f43172f60ULL, 0x84c87814a1f0ab72ULL, 0x8cc702081a6439ecULL,
        0x90befffa23631e28ULL, 0xa4506cebde82bde9ULL, 0xbef9a3f7b2c67915ULL, 0xc67178f2e372532bULL,
        0xca273eceea26619cULL, 0xd186b8c721c0c207ULL, 0xeada7dd6cde0eb1eULL, 0xf57d4f7fee6ed178ULL,
        0x06f067aa72176fbaULL, 0x0a637dc5a2c898a6ULL, 0x113f9804bef90daeULL, 0x1b710b35131c471bULL,
        0x28db77f523047d84ULL, 0x32caab7b40c72493ULL, 0x3c9ebe0a15c9bebcULL, 0x431d67c49c100d4cULL,
        0x4cc5d4becb3e42b6ULL, 0x597f299cfc657e2aULL, 0x5fcb6fab3ad6faecULL, 0x6c44198c4a475817ULL
    };

    memcpy(K , SHA512_K , sizeof(uint64_t)*80) ; 
    
}

static void init_Hash_Values_sha512(uint64_t H[8]) {
    const uint64_t SHA512_H[8] = {
        0x6a09e667f3bcc908ULL,  // square root of 2
        0xbb67ae8584caa73bULL,  // square root of 3
        0x3c6ef372fe94f82bULL,  // square root of 5
        0xa54ff53a5f1d36f1ULL,  // square root of 7
        0x510e527fade682d1ULL,  // square root of 11
        0x9b05688c2b3e6c1fULL,  // square root of 13
        0x1f83d9abfb41bd6bULL,  // square root of 17
        0x5be0cd19137e2179ULL   // square root of 19
    };
    
    
    memcpy(H , SHA512_H , sizeof(uint64_t)*8) ; 


}


uchar_t* sha512_padding(const uchar_t M[] , uint64_t b , uint64_t *output_length ) {
    // b number of bits 
    *output_length = b +64 +  (1024 - ((b+64)  % 1024)) ;

    uchar_t *output = malloc(*output_length * sizeof(uchar_t)  ) ;
    if (b % 8 == 0)
    {
        memcpy(output , M  , sizeof(uchar_t)* b / 8) ;
        uint32_t temp = (b / 8) % 128  ;
        uint32_t index =  b / 8 ;

        output[index] = 0x80 ;
        index++ ;
        temp++ ;

        
        while (temp % 128 != 112)
        {
            output[index] = 0x00 ;
            index++ ;
            temp++ ;
        }

        output[index]   = 0x00 ; 
        output[index+1] = 0x00 ; 
        output[index+2] = 0x00 ; 
        output[index+3] = 0x00 ; 
        
        index += 4 ; 
        

        output[index]   = 0x00 ; 
        output[index+1] = 0x00 ; 
        output[index+2] = 0x00 ; 
        output[index+3] = 0x00 ; 
        
        index += 4 ; 
        
        output[index] =   (b & 0xff00000000000000 ) >> 56 ; 
        output[index+1] = (b & 0x00ff000000000000 ) >> 48 ; 
        output[index+2] = (b & 0x0000ff0000000000 ) >> 40; 
        output[index+3] = (b & 0x000000ff00000000 ) >> 32; 
        
        index += 4 ; 
        
        output[index] =   (b & 0x00000000ff000000 ) >> 24 ; 
        output[index+1] = (b & 0x0000000000ff0000 ) >> 16 ; 
        output[index+2] = (b & 0x000000000000ff00 ) >> 8; 
        output[index+3] = (b & 0x00000000000000ff ); 
        
        
        index += 4 ; 


        // printf("calculated output length : %ld \n" , *output_length ) ;
        // printf("calculated output length/8 : %ld \n" , *output_length / 8) ;
        // printf("index : %u \n" , index) ;
        *output_length = index *8; 
        assert(index == *output_length / 8 && "these 2 should be equal ???") ;
    } else {
        // ????????????????????????
        // TODO : handle this case too ...
        // ????????????????????????
        printf("not implemented (my pc works with only 8 bits :( \n")  ;
        exit(12) ;
    }

    return output ;

}

// man dont let anyone read this poor implementation ...
// i chose a different approach which is to just deal with the input as raw bytes
void sha512_hash(const uchar_t* data, size_t len, uchar_t digest[64]) {
    uint64_t H[8] ; 
    uchar_t W[80*8] ; 
    uint64_t K[80] ; 

    init_K_sha512(K);
    init_Hash_Values_sha512(H) ;



    // PRINT_ARRAY(K , 80 , "%lx") ; 
    // PRINT_ARRAY(H , 8 , "%lx") ; 

    uint64_t output_length  ; 
    uchar_t *input_padded = sha512_padding(data , 8*len , &output_length) ; 
    output_length /= 8 ; 

    // PRINT_ARRAY(input_padded , output_length , "%.02x") ; 


    uint64_t a , b , c , d , e ,f , g, h ;
    // int j =0 ;
    // printf("N =  %d\n" , output_length) ; 
    // printf("here you go looping from 0 to N/(16*8)-1 : %d\n" , output_length/(16*8)-1) ; 
    for (size_t i = 0; i <= output_length/(16*8)-1; i++)
    {
        for (size_t t = 0; t < 16; t++)
        {
            memcpy(W + (t*8) , input_padded + (t*8 ) + (i*8*16) , sizeof(uint64_t )  * 1) ; 
        }
        for (size_t t = 16; t < 80; t++)
        {
            uint64_t result = Sigma1_512_sha512(bytes_to_64be(W + (t -2)*8)) + bytes_to_64be(W + (t -7)*8) + Sigma0_512_sha512(bytes_to_64be(W + (t -15)*8)) + bytes_to_64be(W + (t -16)*8)    ; 
            be64_to_bytes(result , W + t*8 ) ;

        }
        
        a = H[0] ; 
        b = H[1] ; 
        c = H[2] ; 
        d = H[3] ; 
        e = H[4] ; 
        f = H[5] ; 
        g = H[6] ; 
        h = H[7] ; 
        
        uint64_t T1 ;
        uint64_t T2 ;
        
        for (size_t t = 0; t < 80; t++)
        {

                
            T1 = (uint64_t) (h + Sum1_512_sha512(e) + Ch_sha512(e , f , g ) + K[t] + bytes_to_64be(W + t*8))   ;  
            T2 = (uint64_t) ( Sum0_512_sha512(a) + Maj_sha512(a , b , c ) )   ;  

            h = g ;
            
            g = f ; 
            
            f = e ; 
            
            e = d + T1 ; 
            
            d = c ; 
            
            c = b ;
            
            b = a ; 
            
            a = T1 + T2 ;

        }

        H [0] =  a  +  H [0] ; 
        H [1] =  b  +  H [1] ; 
        H [2] =  c  +  H [2] ; 
        H [3] =  d  +  H [3] ; 
        H [4] =  e  +  H [4] ; 
        H [5] =  f  +  H [5] ; 
        H [6] =  g  +  H [6] ; 
        H [7] =  h  +  H [7] ; 
    }
  
    be64_to_bytes( H[0] , digest + 0 * 8 ) ; 
    be64_to_bytes( H[1] , digest + 1 * 8 ) ; 
    be64_to_bytes( H[2] , digest + 2 * 8 ) ; 
    be64_to_bytes( H[3] , digest + 3 * 8 ) ; 
    be64_to_bytes( H[4] , digest + 4 * 8 ) ; 
    be64_to_bytes( H[5] , digest + 5 * 8 ) ; 
    be64_to_bytes( H[6] , digest + 6 * 8 ) ; 
    be64_to_bytes( H[7] , digest + 7 * 8 ) ; 


    free(input_padded) ; 
}

